title: this_is_the_way
email: your-email@example.com
description: >-
only blog
baseurl: "" 
url: "" 
twitter_username: jekyllrb
github_username:  jekyll

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

